### ISSUE TITLE
Missing model `trocr-large-handwritten-fr`

### ISSUE THREAD

**Issue by quachpas** [handwrittenOCR/trocr_handwritten#1]
Hello!
Unfortunately looks like the model `trocr-large-handwritten-fr` is not on huggingface anymore. I can only find the `trocr-base-printed-fr`.
@agombert, do you think you could put it online again?
Best,

**Comment by agombert** [comment]
Hello @quachpas, it should be online again soon in 2024. It does not depend only on me unfortunately 😶‍🌫️

**Comment by Oyabi** [comment]
Any idea when it will be available?

**Comment by agombert** [comment]
Hey, sorry for the delay, between work and holidays I could not do it sooner. Now the model is public ! 🎉
